version: '3.5'

networks:
  minio:
    name: minio
    driver: bridge

services:
  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    container_name: minio.infra.local
    restart: always
    command:
      - server
      - --certs-dir=/minio/certs
      - /minio/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - /mnt/data/infra/minio/data:/minio/data
      - /mnt/data/infra/minio/certs:/minio/certs
    networks:
      - minio
    ports:
      - 9000:9000
    expose:
      - "9000"

