version: '3.5'

networks:
  minio:
    name: minio
    driver: bridge

services:
  minio:
    image: minio/minio
    container_name: minio.local
    restart: always
    command:
      - server
      - /data
    environment: {}
    volumes:
      - /mnt/data/infra/minio/data:/data
    networks:
      - minio
    ports:
      - 9000:9000
    expose:
      - "9000"

